import type { Metadata } from "next";

import React from 'react'

export const metadata: Metadata = {
    title: "My Schedule - Proyek",
    description: "Generated by create next app",
};

export default function page() {
    return (
        <div>page</div>
    )
}
